### ISSUE TITLE
Add contact information to the readme

### ISSUE THREAD

**Issue by yrshaikh** [dpaquette/BugTracker.NET#32]
Hi,

Corey directed me to this repo on github. Cudnt find any other way to contact you guys.

Regards,
Yasser Shaikh

**Comment by stimms** [comment]
Hi Yasser, 

You can contact us @Dave_Paquette or @stimms on twitter. I've updated the Readme to reflect that. We'd be happy to have contributors. Feel free to open issues and submit pull requests.

**Comment by yrshaikh** [comment]
@stimms Hey, missed out on this message somehow. Thanks for your response. I ll check the repo this weekend. Cheers :)
